--------------------------------------------------------------------------------
-- SCRIPT XÓA (DROP) CÁC BẢNG CŨ TRONG EWALLET
--------------------------------------------------------------------------------

-- Nhóm bảng Log & Hoạt động (Bảng con cấp thấp)
DROP TABLE audit_logs CASCADE CONSTRAINTS;
DROP TABLE account_activity_logs CASCADE CONSTRAINTS;
DROP TABLE login_sessions CASCADE CONSTRAINTS;

-- Nhóm bảng Fraud (Các bảng bạn muốn loại bỏ)
DROP TABLE fraud_flags CASCADE CONSTRAINTS;
DROP TABLE fraud_rules CASCADE CONSTRAINTS;

-- Nhóm bảng Phân quyền (Các bảng bạn muốn loại bỏ)
DROP TABLE user_roles CASCADE CONSTRAINTS;
DROP TABLE roles CASCADE CONSTRAINTS;

-- Nhóm bảng Giao dịch & Nạp/Rút
DROP TABLE fund_orders CASCADE CONSTRAINTS;
DROP TABLE transactions CASCADE CONSTRAINTS;
DROP TABLE transaction_fees CASCADE CONSTRAINTS;
DROP TABLE transaction_limits CASCADE CONSTRAINTS;
DROP TABLE transaction_types CASCADE CONSTRAINTS;
DROP TABLE transaction_ref_sequences CASCADE CONSTRAINTS;

-- Nhóm bảng Phương thức & Ví
DROP TABLE payment_methods CASCADE CONSTRAINTS;
DROP TABLE wallets CASCADE CONSTRAINTS;
DROP TABLE vouchers CASCADE CONSTRAINTS;

-- Nhóm bảng Cốt lõi (Bảng cha cao nhất)
DROP TABLE users CASCADE CONSTRAINTS;

-- SCRIPT TẠO DB
-- 1. Bảng USERS
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    full_name VARCHAR2(100),
    email VARCHAR2(150) UNIQUE, 
    phone VARCHAR2(15) UNIQUE,
    password_hash VARCHAR2(255),
    kyc_status VARCHAR2(20) DEFAULT 'VERIFIED',
    is_active NUMBER(1) DEFAULT 1, 
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP
);

-- 2. Bảng TRANSACTION_TYPES
CREATE TABLE transaction_types (
    type_id NUMBER(5) PRIMARY KEY, 
    type_code VARCHAR2(20) UNIQUE, 
    description VARCHAR2(255) 
);

-- 3. Bảng TRANSACTION_LIMITS
CREATE TABLE transaction_limits (
    limit_id NUMBER(10) PRIMARY KEY,
    kyc_level VARCHAR2(20),
    max_amount_per_trans NUMBER(18, 4), 
    max_amount_per_day NUMBER(18, 4), 
    max_trans_per_day NUMBER(10) 
);

-- 4. Bảng VOUCHERS
CREATE TABLE vouchers (
    voucher_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    code VARCHAR2(20) UNIQUE, 
    discount_type VARCHAR2(20), 
    discount_value NUMBER(18,4), 
    min_order_value NUMBER(18,4), 
    max_discount NUMBER(18,4), 
    valid_until TIMESTAMP,
    amount_vouchers NUMBER(10) DEFAULT 0,  -- Bổ sung theo PDF
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP
);

-- 5. Bảng TRANSACTION_REF_SEQUENCES (Hỗ trợ sinh mã tự động)
CREATE TABLE transaction_ref_sequences (
    ref_date DATE PRIMARY KEY,
    current_value NUMBER(10) DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ==============================================================================
-- PHẦN 2: TẠO CÁC BẢNG CÓ KHÓA NGOẠI (CHILD TABLES)
-- ==============================================================================

-- 6. Bảng WALLETS
CREATE TABLE wallets (
    wallet_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    user_id NUMBER UNIQUE, 
    balance NUMBER(18,4) DEFAULT 0, 
    currency VARCHAR2(10) DEFAULT 'VND',
    wallet_status VARCHAR2(20) DEFAULT 'ACTIVE', 
    pin_code VARCHAR2(6), -- Bổ sung theo PDF (Mã PIN 6 số)
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP, 
    updated_at TIMESTAMP, 
    CONSTRAINT fk_wallet_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- 7. Bảng PAYMENT_METHODS
CREATE TABLE payment_methods (
    method_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER, 
    method_type VARCHAR2(20), 
    provider_name VARCHAR2(100), 
    masked_number VARCHAR2(20),
    is_default NUMBER(1) DEFAULT 0,
    is_verified NUMBER(1) DEFAULT 0, 
    is_active NUMBER(1) DEFAULT 1, -- Bổ sung theo PDF
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_payment_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- 8. Bảng TRANSACTION_FEES
CREATE TABLE transaction_fees (
    fee_id NUMBER(10) PRIMARY KEY, 
    type_id NUMBER(5), 
    fee_rate NUMBER(5,4), 
    fee_fixed NUMBER(18,4),
    min_fee NUMBER(18,4),
    max_fee NUMBER(18,4), 
    effective_from DATE,
    effective_to DATE,
    CONSTRAINT fk_fee_type FOREIGN KEY (type_id) REFERENCES transaction_types(type_id)
);

-- 9. Bảng LOGIN_SESSIONS
CREATE TABLE login_sessions (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER, 
    device_info VARCHAR2(255), 
    ip_address VARCHAR2(45), 
    is_active NUMBER(1) DEFAULT 1, 
    CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- 10. Bảng FUND_ORDERS
CREATE TABLE fund_orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    wallet_id NUMBER,
    method_id NUMBER, 
    order_type VARCHAR2(20),
    amount NUMBER(18, 4), 
    status VARCHAR2(20) DEFAULT 'PENDING',
    idempotency_key VARCHAR2(100) UNIQUE, 
    gateway_ref VARCHAR2(100),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_fund_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(wallet_id),
    CONSTRAINT fk_fund_method FOREIGN KEY (method_id) REFERENCES payment_methods(method_id)
);

-- 11. Bảng TRANSACTIONS
CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    type_id NUMBER(5),
    sender_wallet_id NUMBER, 
    receiver_wallet_id NUMBER, 
    limit_id NUMBER(10),
    voucher_id NUMBER, 
    original_transaction_id NUMBER, -- Hỗ trợ reverse/refund
    amount NUMBER(18, 4), 
    fee_amount NUMBER(18, 4) DEFAULT 0, 
    status VARCHAR2(20) DEFAULT 'PENDING',
    reference_code VARCHAR2(50) UNIQUE, 
    step NUMBER(10),
    description VARCHAR2(500),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP, 
    updated_at TIMESTAMP,
    CONSTRAINT fk_trans_type FOREIGN KEY (type_id) REFERENCES transaction_types(type_id),
    CONSTRAINT fk_trans_sender FOREIGN KEY (sender_wallet_id) REFERENCES wallets(wallet_id),
    CONSTRAINT fk_trans_receiver FOREIGN KEY (receiver_wallet_id) REFERENCES wallets(wallet_id),
    CONSTRAINT fk_trans_limit FOREIGN KEY (limit_id) REFERENCES transaction_limits(limit_id),
    CONSTRAINT fk_trans_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers(voucher_id),
    CONSTRAINT fk_trans_original FOREIGN KEY (original_transaction_id) REFERENCES transactions(transaction_id)
);

-- 12. Bảng AUDIT_LOGS
CREATE TABLE audit_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    transaction_id NUMBER,
    wallet_id NUMBER, 
    action_type VARCHAR2(10), 
    balance_before NUMBER(18, 4), 
    balance_after NUMBER(18, 4), 
    delta NUMBER(18, 4), 
    CONSTRAINT fk_audit_trans FOREIGN KEY (transaction_id) REFERENCES transactions(transaction_id),
    CONSTRAINT fk_audit_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(wallet_id)
);

-- ==============================================================================
-- PHẦN 3: RÀNG BUỘC (CHECK CONSTRAINTS) & INDEXES
-- ==============================================================================

-- USERS
ALTER TABLE users ADD CONSTRAINT chk_users_is_active CHECK (is_active IN (0, 1));
ALTER TABLE users ADD CONSTRAINT chk_users_kyc_status CHECK (kyc_status IN ('PENDING', 'VERIFIED', 'REJECTED'));
ALTER TABLE users ADD CONSTRAINT chk_users_updated_at CHECK (updated_at IS NULL OR created_at IS NULL OR created_at <= updated_at);

-- WALLETS
ALTER TABLE wallets ADD CONSTRAINT chk_wallets_balance CHECK (balance >= 0);
ALTER TABLE wallets ADD CONSTRAINT chk_wallets_status CHECK (wallet_status IN ('ACTIVE', 'FROZEN', 'CLOSED'));
ALTER TABLE wallets ADD CONSTRAINT chk_wallets_updated_at CHECK (updated_at IS NULL OR created_at IS NULL OR created_at <= updated_at);

-- PAYMENT_METHODS
ALTER TABLE payment_methods ADD CONSTRAINT chk_pm_method_type CHECK (method_type IN ('BANK_ACCOUNT', 'CREDIT_CARD'));
ALTER TABLE payment_methods ADD CONSTRAINT chk_pm_is_default CHECK (is_default IN (0, 1));
ALTER TABLE payment_methods ADD CONSTRAINT chk_pm_is_verified CHECK (is_verified IN (0, 1));
ALTER TABLE payment_methods ADD CONSTRAINT chk_pm_is_active CHECK (is_active IN (0, 1));
ALTER TABLE payment_methods ADD CONSTRAINT chk_pm_updated_at CHECK (updated_at IS NULL OR created_at IS NULL OR created_at <= updated_at);
CREATE UNIQUE INDEX uq_pm_default ON payment_methods (CASE WHEN is_default = 1 THEN user_id ELSE NULL END);

-- TRANSACTION_LIMITS
ALTER TABLE transaction_limits ADD CONSTRAINT chk_tlimit_kyc_level CHECK (kyc_level IN ('UNVERIFIED', 'VERIFIED'));
ALTER TABLE transaction_limits ADD CONSTRAINT chk_tlimit_positive CHECK (max_amount_per_trans > 0 AND max_amount_per_day > 0 AND max_trans_per_day > 0);
ALTER TABLE transaction_limits ADD CONSTRAINT chk_tlimit_logic CHECK (max_amount_per_trans <= max_amount_per_day);

-- VOUCHERS
ALTER TABLE vouchers ADD CONSTRAINT chk_vouchers_discount_val CHECK (discount_value >= 0);
ALTER TABLE vouchers ADD CONSTRAINT chk_vouchers_discount_type CHECK (discount_type IN ('FIXED', 'PERCENTAGE'));
ALTER TABLE vouchers ADD CONSTRAINT chk_vouchers_amount_count CHECK (amount_vouchers >= 0);
ALTER TABLE vouchers ADD CONSTRAINT chk_vouchers_is_active CHECK (is_active IN (0, 1));
ALTER TABLE vouchers ADD CONSTRAINT chk_vouchers_min_order CHECK (min_order_value IS NULL OR min_order_value >= 0);
ALTER TABLE vouchers ADD CONSTRAINT chk_vouchers_max_discount CHECK (max_discount IS NULL OR max_discount >= 0);
ALTER TABLE vouchers ADD CONSTRAINT chk_vouchers_updated_at CHECK (updated_at IS NULL OR created_at IS NULL OR created_at <= updated_at);

-- TRANSACTION_FEES
ALTER TABLE transaction_fees ADD CONSTRAINT chk_tfees_positive CHECK (fee_rate >= 0 AND fee_fixed >= 0 AND min_fee >= 0);
ALTER TABLE transaction_fees ADD CONSTRAINT chk_tfees_min_max CHECK (max_fee IS NULL OR min_fee <= max_fee);
ALTER TABLE transaction_fees ADD CONSTRAINT chk_tfees_rate_range CHECK (fee_rate BETWEEN 0 AND 1);
ALTER TABLE transaction_fees ADD CONSTRAINT chk_tfees_effective_dates CHECK (effective_to IS NULL OR effective_from <= effective_to);

-- LOGIN_SESSIONS
ALTER TABLE login_sessions ADD CONSTRAINT chk_lsessions_is_active CHECK (is_active IN (0, 1));

-- FUND_ORDERS
ALTER TABLE fund_orders ADD CONSTRAINT chk_forders_order_type CHECK (order_type IN ('TOP_UP', 'WITHDRAW'));
ALTER TABLE fund_orders ADD CONSTRAINT chk_forders_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED'));
ALTER TABLE fund_orders ADD CONSTRAINT chk_forders_amount CHECK (amount > 0);
ALTER TABLE fund_orders ADD CONSTRAINT chk_forders_updated_at CHECK (updated_at IS NULL OR created_at IS NULL OR created_at <= updated_at);

-- TRANSACTIONS
ALTER TABLE transactions ADD CONSTRAINT chk_trans_wallets CHECK (sender_wallet_id IS NULL OR receiver_wallet_id IS NULL OR sender_wallet_id <> receiver_wallet_id);
ALTER TABLE transactions ADD CONSTRAINT chk_trans_amounts CHECK (amount > 0 AND fee_amount >= 0);
ALTER TABLE transactions ADD CONSTRAINT chk_trans_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'REVERSED'));
ALTER TABLE transactions ADD CONSTRAINT chk_trans_original_not_self CHECK (original_transaction_id IS NULL OR original_transaction_id <> transaction_id);
ALTER TABLE transactions ADD CONSTRAINT chk_trans_updated_at CHECK (updated_at IS NULL OR created_at IS NULL OR created_at <= updated_at);

-- AUDIT_LOGS
ALTER TABLE audit_logs ADD CONSTRAINT chk_alogs_action_type CHECK (action_type IN ('DEBIT', 'CREDIT'));
ALTER TABLE transaction_ref_sequences ADD CONSTRAINT chk_refseq_current_value CHECK (current_value >= 0);

-- ==============================================================================
-- PHẦN 4: TRIGGERS (TỰ ĐỘNG CẬP NHẬT UPDATED_AT & BẢO VỆ DỮ LIỆU)
-- ==============================================================================

CREATE OR REPLACE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_wallets_set_updated_at
BEFORE UPDATE ON wallets
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_pm_set_updated_at
BEFORE UPDATE ON payment_methods
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_forders_set_updated_at
BEFORE UPDATE ON fund_orders
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_trans_set_updated_at
BEFORE UPDATE ON transactions
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_vouchers_set_updated_at
BEFORE UPDATE ON vouchers
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- Bảo vệ AUDIT_LOGS: Chỉ được INSERT, không được UPDATE/DELETE sau khi tạo.
CREATE OR REPLACE TRIGGER trg_prevent_audit_log_u_d
BEFORE UPDATE OR DELETE ON audit_logs
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(
        -20001,
        'AUDIT_LOGS cannot be updated or deleted after creation.'
    );
END;
/

-- ==============================================================================
-- PHẦN 5: SEED DATA (DỮ LIỆU MẪU CHO LOẠI GIAO DỊCH)
-- ==============================================================================

INSERT INTO transaction_types (type_id, type_code, description) VALUES (1, 'TOP_UP', 'Nạp tiền vào ví');
INSERT INTO transaction_types (type_id, type_code, description) VALUES (2, 'WITHDRAW', 'Rút tiền khỏi ví');
INSERT INTO transaction_types (type_id, type_code, description) VALUES (3, 'TRANSFER', 'Chuyển tiền giữa hai ví');
INSERT INTO transaction_types (type_id, type_code, description) VALUES (4, 'PAYMENT', 'Thanh toán bằng số dư ví');
INSERT INTO transaction_types (type_id, type_code, description) VALUES (5, 'REVERSAL', 'Giao dịch đảo ngược giao dịch đã hoàn tất');
INSERT INTO transaction_types (type_id, type_code, description) VALUES (6, 'REFUND', 'Giao dịch hoàn tiền');

COMMIT;