-- 1. TẠO CÁC BẢNG ĐỘC LẬP (MASTER TABLES)

-- Bảng USERS
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    full_name VARCHAR2(100),
    email VARCHAR2(150) UNIQUE, 
    phone VARCHAR2(15) UNIQUE,
    password_hash VARCHAR2(255),
    kyc_status VARCHAR2(20),
    is_active NUMBER(1), 
    created_at TIMESTAMP 
);

-- Bảng TRANSACTION_TYPES
CREATE TABLE transaction_types (
    type_id NUMBER(5) PRIMARY KEY, 
    type_code VARCHAR2(20) UNIQUE, 
    description VARCHAR2(255) 
);

-- Bảng TRANSACTION_LIMITS
CREATE TABLE transaction_limits (
    limit_id NUMBER(10) PRIMARY KEY,
    kyc_level VARCHAR2(20),
    max_amount_per_trans NUMBER(18, 4), 
    max_amount_per_day NUMBER(18, 4), 
    max_trans_per_day NUMBER(10) 
);

-- Bảng VOUCHERS
CREATE TABLE vouchers (
    voucher_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    code VARCHAR2(20) UNIQUE, 
    discount_type VARCHAR2(20), 
    discount_value NUMBER(18,4), 
    min_order_value NUMBER(18,4), 
    max_discount NUMBER(18,4), 
    valid_until TIMESTAMP 
);

-- Bảng FRAUD_RULES
CREATE TABLE fraud_rules (
    rule_id NUMBER(10) PRIMARY KEY, 
    rule_name VARCHAR2(100), 
    condition_field VARCHAR2(50), 
    operator VARCHAR2(10), 
    threshold_value NUMBER(18, 4), 
    action VARCHAR2(20) 
);

-- 2. TẠO CÁC BẢNG CÓ KHÓA NGOẠI (CHILD TABLES)

-- Bảng WALLETS
CREATE TABLE wallets (
    wallet_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    user_id NUMBER UNIQUE, 
    balance NUMBER(18,4), 
    currency VARCHAR2(10) DEFAULT 'VND',
    wallet_status VARCHAR2(20), 
    created_at TIMESTAMP, 
    updated_at TIMESTAMP, 
    CONSTRAINT fk_wallet_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Bảng PAYMENT_METHODS
CREATE TABLE payment_methods (
    method_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER, 
    method_type VARCHAR2(20), 
    provider_name VARCHAR2(100), 
    masked_number VARCHAR2(20),
    is_default NUMBER(1),
    is_verified NUMBER(1), 
    CONSTRAINT fk_payment_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Bảng TRANSACTION_FEES
CREATE TABLE transaction_fees (
    fee_id NUMBER(10) PRIMARY KEY, 
    type_id NUMBER(5), 
    fee_rate NUMBER(5,4), 
    fee_fixed NUMBER(18,4),
    min_fee NUMBER(18,4),
    max_fee NUMBER(18,4), 
    effective_from DATE,
    effective_to DATE,
    CONSTRAINT fk_fee_type FOREIGN KEY (type_id) REFERENCES transaction_types(type_id)
);

-- Bảng LOGIN_SESSIONS
CREATE TABLE login_sessions (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER, 
    device_info VARCHAR2(255), 
    ip_address VARCHAR2(45), 
    is_active NUMBER(1), 
    CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Bảng FUND_ORDERS
CREATE TABLE fund_orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    wallet_id NUMBER,
    method_id NUMBER, 
    order_type VARCHAR2(20),
    amount NUMBER(18, 4), 
    status VARCHAR2(20),
    idempotency_key VARCHAR2(100) UNIQUE, 
    gateway_ref VARCHAR2(100),
    CONSTRAINT fk_fund_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(wallet_id),
    CONSTRAINT fk_fund_method FOREIGN KEY (method_id) REFERENCES payment_methods(method_id)
);

-- Bảng TRANSACTIONS
CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    type_id NUMBER(5),
    sender_wallet_id NUMBER, -- Có thể NULL 
    receiver_wallet_id NUMBER, -- Có thể NULL 
    limit_id NUMBER(10),
    voucher_id NUMBER, 
    amount NUMBER(18, 4), 
    fee_amount NUMBER(18, 4), 
    status VARCHAR2(20),
    reference_code VARCHAR2(50) UNIQUE, 
    step NUMBER(10),
    created_at TIMESTAMP, 
    CONSTRAINT fk_trans_type FOREIGN KEY (type_id) REFERENCES transaction_types(type_id),
    CONSTRAINT fk_trans_sender FOREIGN KEY (sender_wallet_id) REFERENCES wallets(wallet_id),
    CONSTRAINT fk_trans_receiver FOREIGN KEY (receiver_wallet_id) REFERENCES wallets(wallet_id),
    CONSTRAINT fk_trans_limit FOREIGN KEY (limit_id) REFERENCES transaction_limits(limit_id),
    CONSTRAINT fk_trans_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers(voucher_id)
);

-- Bảng FRAUD_FLAGS
CREATE TABLE fraud_flags (
    flag_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    transaction_id NUMBER, 
    rule_id NUMBER(10), 
    risk_score NUMBER(4,2), 
    action_taken VARCHAR2(20), 
    is_confirmed NUMBER(1), 
    CONSTRAINT fk_fraud_trans FOREIGN KEY (transaction_id) REFERENCES transactions(transaction_id),
    CONSTRAINT fk_fraud_rule FOREIGN KEY (rule_id) REFERENCES fraud_rules(rule_id)
);

-- Bảng AUDIT_LOGS
CREATE TABLE audit_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    transaction_id NUMBER,
    wallet_id NUMBER, 
    action_type VARCHAR2(10), 
    balance_before NUMBER(18, 4), 
    balance_after NUMBER(18, 4), 
    delta NUMBER(18, 4), 
    CONSTRAINT fk_audit_trans FOREIGN KEY (transaction_id) REFERENCES transactions(transaction_id),
    CONSTRAINT fk_audit_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(wallet_id)
);